name: ci
on:
        push:
                branches:
                        - main
                        - build_makefile  
                        - prexte-patch-1
permissions:
        contents: read        

jobs:
        build_and_check:
                name: Build and Check
                runs-on: ubuntu-latest
                container:
                        image: prexte/avr-gcc:latest
                steps:
                        - name: Checkout the repository
                          uses: actions/checkout@v4
                        - run: make  
                        - name: Store Artifacts
                          uses: actions/upload-artifact@v4
                          with: 
                                  path: ./build/bin/*.hex
        upload_firmware:
                name: Upload Firmware
                needs: build_and_check
                runs-on: self-hosted
                steps:
                        - name: Download Artifacts
                          uses: actions/download-artifact@v4
                        - name: List Downloaded File
                          run: "dir /s /b"
                        - name: AVRDude upload Firmware
                          run: "F:\avrdude\avrdude.exe -c usbasp -p t2313 -U flash:w:./artifact/h_bridge.hex:i -B4"
                          
                                  
                
                                  
