name: ci
on:
        push:
                branches:
                        - main
permissions:
        contents: read        

jobs:
        build:
                runs-on: ubuntu-latest
                container:
                        image: prexte/test:latest
                steps:
                        - name: Checkout the repository
                          uses: actions/checkout@v4
                        - run: make  

