on: [push]
jobs:
        build:
                runs-on: ubuntu-latest
                container:
                        image: prexte/avr-gcc:latest
                steps:
                        - name: Checkout the repository
                          uses: actions/checkout@v3
                        - run: make  

