name: ci
on:
        push:
                branches:
                        - main
                        - build_makefile  
                        - prexte-patch-1
permissions:
        contents: read        

jobs:
        build_and_check:
                runs-on: ubuntu-latest
                container:
                        image: prexte/avr-gcc:latest
                steps:
                        - name: Checkout the repository
                          uses: actions/checkout@v4
                        - run: make  
                        - name: Store Artifacts
                          uses: actions/upload-artifact@v4
                          with: 
                                  path: ./build/bin/*.hex
        upload:
                name: Upload
                needs: build_and_check
                runs-on: self-hosted
                steps:
                        - name: Download Artifacts
                          uses: actions/download-artifact@v4
                          with:
                                  name: h_bridge.hex
                        - name: List Downloaded File
                        - run: dir
                                  
                
                                  
